// Writes server/systems/legacy-homes.js: the homes of world v1 (the world before World v2) by index -
// what each one cost and what it was called - so a profile that bought a home there before deeds were
// kept is bought back at the right price when the world changes under it (server/systems/homes.js
// checkWorld). Run once against a checkout of the old world: node tools/world2/legacy-homes.mjs [--root <dir>]
import { writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';

const args = process.argv.slice(2);
const i = args.indexOf('--root');
const root = resolve(i >= 0 ? args[i + 1] : new URL('../..', import.meta.url).pathname);
const out = resolve(new URL('../../server/systems/legacy-homes.js', import.meta.url).pathname);
const { generateCity } = await import(pathToFileURL(join(root, 'shared/map.js')).href);
const m = generateCity(1337);
const rows = m.homes.map((h) => `  [${h.price}, ${JSON.stringify(h.name)}],`);
writeFileSync(out, `// GENERATED by tools/world2/legacy-homes.mjs - do not edit by hand.
// The homes of world v1 by index: [price paid, name]. Profiles from before deeds were kept refer to
// their homes only by index; when the world changes, these are what they get bought back at.
export const LEGACY_HOMES = {
 1: [
${rows.join('\n')}
 ],
};
`);
console.log(`${out}: ${m.homes.length} homes`);
