// Each instrument's level trim in dB (generated by tools/sound/bench.py --levels from a render of every recipe alone:
// its loudest 200 ms, A-weighted, brought to its category's target - test/fixtures/sound-levels.json has the
// measurements; test/sound.test.js checks them). engine.js play multiplies a sound's volume by its trim.
export const TRIM_DB = Object.freeze({
  airbrake: -8.4, alarmbell: 4.1, alert: 2.4, babble: 17.7, bad: 4.2, baton: 6.7, bats: 10.1, bell: 0,
  bellow: 2.2, bikebell: -3, bird: 0.7, bite: -1.7, bodyfall: 9.1, bonk: 4, burner: 2.5, camera: 3.4,
  cardoor: 6.4, cashin: -5.5, cashout: 6.6, cashtoss: 3.2, cast: 5.2, cavedrip: -0.6, chainsaw: 2.5, checkpoint: 5.9,
  chop: 4.5, churchbell: -6.2, churchbells: -6.4, clack: -2.5, clang: -2.4, clank: 1.7, click: 8.9, coin: -5.8,
  crackle: 12.1, crash: -6, cricket: 8, cut: 5, death: -4.1, deposit: -1.9, dog: 4.5, doorbell: -6.4,
  douse: 0.5, drip: -4.4, drop: 20.0, enginestart: 3.5, explosion: -2.7, farhorn: 2.1, farsiren: -6.2, flarestrike: -0.4,
  flutter: 3.1, foliage: 1.8, gate: 1, gatearm: 9, glass: 0.3, goal: 1.1, golfcup: 0.8, golfhit: 4.1,
  good: -8.7, growl: 5.3, gull: 4.2, gun_pistol: 2.8, gun_revolver: 2.5, gun_rifle: 3.4, gun_rocket: 4.9, gun_shotgun: 1.9,
  gun_silenced: 5.7, gun_smg: 11, gun_sniper: 2.2, gush: -8, heal: 1.1, hit: 14, honk: 7.7, hoopin: 5.7,
  housedoor: 7.7, hum: 8.3, ignite: 4, impact: 5, impact_flesh: 9.1, impact_wood: 4.7, kick: 5.7, knockdown: 5.6,
  leaves: 0.9, lightclick: 16.6, manhole: 2.9, notify: -0.3, orefree: 3.2, owl: -1.9, paper: 4.6, phoneclose: 2.9,
  phoneopen: 1, pickaxe: 3.2, pickup: 7.7, pluck: 9, poof: 9.2, punch: 4.9, putt: 9.5, racego: -6.5,
  reloadin: 0.9, reloadout: 3.5, revive: 9.3, ricochet: 3.7, ridebell: -5.6, rockfall: 6.1, roll: 7.1, rollerdoor: 8.2,
  rubble: 1.9, scrape: 4.6, scream: 1.4, screech: 2, sear: 4.5, shutter: 12.2, slash: 5.4, slidingdoor: 6.2,
  spikes: 7.6, splash: -4, spray: 4.3, squeak: 4.3, stab: 8.3, stardown: 5.8, starup: 0, step: 5.9,
  stroke: -5.4, swish: 3.4, taser: 4.4, thud: 8.6, thunder: 8.7, thwack: 8.1, trainhorn: -7.8, trainhornshort: -6.9,
  treecrack: -0.2, treefall: 7.4, trickle: 7.3, twang: 7.6, twig: -2.9, tyrepop: -0.5, whoosh: 8.1, whoosh_blade: 5.3,
  whoosh_heavy: 7.7, woodcrunch: 5.1, yelp: 10, zing: 2,
});
