// Generated by tools/build_interiors.py - do not edit.
// Interior paintings for walk-in shops: rect [x, y, w, h] in assets/interiors.webp, door side at the bottom.
export const INTERIOR_RECTS = {"hospital": [0, 0, 512, 492], "corner": [514, 0, 512, 389], "pawn": [0, 494, 512, 347], "boutique": [514, 494, 512, 329], "outfitter": [0, 843, 512, 329], "liquor": [514, 843, 512, 307], "freshmart": [0, 1174, 512, 275], "fuelmart": [514, 1174, 512, 268], "bank": [0, 1451, 512, 249], "police": [514, 1451, 512, 180]};
export const INTERIOR_KINDS = {"convenience": ["liquor", "corner"], "gasstation": ["fuelmart"], "grocery": ["freshmart"], "pawn": ["pawn"], "fence": ["pawn"], "clothing": ["boutique"], "sports": ["outfitter"], "hardware": ["outfitter"], "gunshop": ["outfitter"], "tackle": ["outfitter"], "bank": ["bank"], "courthouse": ["bank"], "hospital": ["hospital"], "pharmacy": ["hospital"], "police": ["police"]};
// Outdoor scene paintings: rect [x, y, w, h] in assets/scenes.webp.
export const SCENE_RECTS = {"golf": [0, 0, 1536, 950]};
