// GENERATED by tools/build_art.py - do not edit by hand.
// Building prefabs cut from the concept building sheet. Sizes/footprints are in tiles
// (32 world px); src is [sheet, x, y, w, h] inside assets/prefabs<sheet>.webp, stored at
// 1 art px per world px (Real-ESRGAN upscaled from the concept sheet).
export const PREFAB_SHEETS = 3;
export const PREFAB_SCALE = 2;
export const PREFABS = {
 "house1": {
  "tw": 7,
  "th": 14,
  "solid": [
   0,
   3,
   7,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   0,
   450,
   964,
   224,
   448
  ]
 },
 "house2": {
  "tw": 7,
  "th": 14,
  "solid": [
   0,
   2,
   7,
   10
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   0,
   676,
   964,
   224,
   448
  ]
 },
 "house3": {
  "tw": 6,
  "th": 14,
  "solid": [
   0,
   2,
   6,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   0,
   902,
   964,
   192,
   448
  ]
 },
 "apt1": {
  "tw": 10,
  "th": 15,
  "solid": [
   1,
   1,
   9,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   0,
   0,
   0,
   320,
   480
  ]
 },
 "apt2": {
  "tw": 10,
  "th": 15,
  "solid": [
   1,
   0,
   9,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   0,
   322,
   0,
   320,
   480
  ]
 },
 "tower1": {
  "tw": 10,
  "th": 15,
  "solid": [
   1,
   0,
   10,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": true,
  "src": [
   0,
   644,
   0,
   320,
   480
  ]
 },
 "tower2": {
  "tw": 7,
  "th": 15,
  "solid": [
   0,
   0,
   7,
   13
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": true,
  "src": [
   0,
   966,
   0,
   224,
   480
  ]
 },
 "hotel": {
  "tw": 11,
  "th": 15,
  "solid": [
   1,
   0,
   10,
   10
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   0,
   1192,
   0,
   352,
   480
  ]
 },
 "hospital": {
  "tw": 18,
  "th": 15,
  "solid": [
   0,
   0,
   18,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   0,
   0,
   482,
   576,
   480
  ]
 },
 "police": {
  "tw": 12,
  "th": 10,
  "solid": [
   1,
   0,
   11,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   1,
   0,
   1158,
   384,
   320
  ]
 },
 "fire": {
  "tw": 12,
  "th": 9,
  "solid": [
   1,
   0,
   12,
   9
  ],
  "doors": [
   0.4
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   2,
   1060,
   0,
   384,
   288
  ]
 },
 "gas": {
  "tw": 13,
  "th": 14,
  "solid": [
   8,
   0,
   13,
   3
  ],
  "doors": [
   0.8
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   0,
   1096,
   964,
   416,
   448
  ]
 },
 "conv": {
  "tw": 13,
  "th": 9,
  "solid": [
   1,
   0,
   13,
   8
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   2,
   1446,
   0,
   416,
   288
  ]
 },
 "strip": {
  "tw": 17,
  "th": 9,
  "solid": [
   0,
   1,
   17,
   8
  ],
  "doors": [
   0.17,
   0.39,
   0.61,
   0.83
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   2,
   0,
   322,
   544,
   288
  ]
 },
 "market": {
  "tw": 17,
  "th": 9,
  "solid": [
   1,
   0,
   17,
   8
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   2,
   546,
   322,
   544,
   288
  ]
 },
 "rest1": {
  "tw": 10,
  "th": 13,
  "solid": [
   1,
   0,
   8,
   7
  ],
  "doors": [
   0.45
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   0,
   1514,
   964,
   320,
   416
  ]
 },
 "rest2": {
  "tw": 9,
  "th": 13,
  "solid": [
   0,
   0,
   9,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   0,
   0,
   1446,
   288,
   416
  ]
 },
 "club": {
  "tw": 11,
  "th": 13,
  "solid": [
   1,
   0,
   10,
   10
  ],
  "doors": [
   0.45
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   0,
   290,
   1446,
   352,
   416
  ]
 },
 "bank": {
  "tw": 14,
  "th": 13,
  "solid": [
   1,
   0,
   13,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   0,
   644,
   1446,
   448,
   416
  ]
 },
 "dealer": {
  "tw": 15,
  "th": 9,
  "solid": [
   3,
   0,
   14,
   9
  ],
  "doors": [
   0.57
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   2,
   1092,
   322,
   480,
   288
  ]
 },
 "repair": {
  "tw": 13,
  "th": 10,
  "solid": [
   1,
   0,
   11,
   9
  ],
  "doors": [
   0.4
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   1,
   386,
   1158,
   416,
   320
  ]
 },
 "warehouse": {
  "tw": 12,
  "th": 9,
  "solid": [
   0,
   0,
   12,
   8
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   2,
   1574,
   322,
   384,
   288
  ]
 },
 "industrial": {
  "tw": 19,
  "th": 15,
  "solid": [
   0,
   0,
   19,
   11
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   0,
   578,
   482,
   608,
   480
  ]
 },
 "construction": {
  "tw": 15,
  "th": 15,
  "solid": [
   4,
   1,
   15,
   11
  ],
  "doors": [
   0.15
  ],
  "ground": "dirt",
  "rot": true,
  "src": [
   0,
   1188,
   482,
   480,
   480
  ]
 },
 "church": {
  "tw": 10,
  "th": 15,
  "solid": [
   1,
   0,
   9,
   11
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   0,
   1670,
   482,
   320,
   480
  ]
 },
 "school": {
  "tw": 14,
  "th": 9,
  "solid": [
   0,
   0,
   14,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   2,
   0,
   612,
   448,
   288
  ]
 },
 "park": {
  "tw": 14,
  "th": 15,
  "solid": [
   4,
   1,
   10,
   7
  ],
  "doors": [
   0.5
  ],
  "ground": "grass",
  "rot": true,
  "src": [
   0,
   0,
   964,
   448,
   480
  ]
 },
 "fuel": {
  "tw": 19,
  "th": 8,
  "solid": [
   11,
   0,
   19,
   7
  ],
  "doors": [
   0.8
  ],
  "ground": "lot",
  "rot": false,
  "scene": true,
  "src": [
   2,
   0,
   902,
   608,
   256
  ]
 },
 "clubnova": {
  "tw": 18,
  "th": 12,
  "solid": [
   0,
   0,
   18,
   8
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   1,
   0,
   418,
   576,
   384
  ]
 },
 "clubeclipse": {
  "tw": 17,
  "th": 11,
  "solid": [
   0,
   0,
   17,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   1,
   0,
   804,
   544,
   352
  ]
 },
 "police2": {
  "tw": 16,
  "th": 13,
  "solid": [
   0,
   0,
   16,
   10
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   0,
   1094,
   1446,
   512,
   416
  ]
 },
 "police3": {
  "tw": 12,
  "th": 13,
  "solid": [
   0,
   1,
   12,
   11
  ],
  "doors": [
   0.6
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   0,
   1608,
   1446,
   384,
   416
  ]
 },
 "motors": {
  "tw": 15,
  "th": 13,
  "solid": [
   1,
   0,
   14,
   7
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "scene": true,
  "src": [
   1,
   0,
   0,
   480,
   416
  ]
 },
 "trail": {
  "tw": 15,
  "th": 11,
  "solid": [
   0,
   0,
   15,
   10
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "scene": true,
  "src": [
   1,
   546,
   804,
   480,
   352
  ]
 },
 "boutique": {
  "tw": 17,
  "th": 11,
  "solid": [
   0,
   0,
   17,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   1,
   1028,
   804,
   544,
   352
  ]
 },
 "quickstop": {
  "tw": 13,
  "th": 11,
  "solid": [
   0,
   0,
   13,
   10
  ],
  "doors": [
   0.45
  ],
  "ground": "lot",
  "rot": false,
  "scene": true,
  "src": [
   1,
   1574,
   804,
   416,
   352
  ]
 },
 "apt3": {
  "tw": 19,
  "th": 9,
  "solid": [
   0,
   0,
   19,
   6
  ],
  "doors": [
   0.25
  ],
  "ground": "plaza",
  "rot": true,
  "scene": true,
  "src": [
   2,
   450,
   612,
   608,
   288
  ]
 },
 "apt4": {
  "tw": 18,
  "th": 12,
  "solid": [
   0,
   2,
   18,
   11
  ],
  "doors": [
   0.45
  ],
  "ground": "grass",
  "rot": true,
  "scene": true,
  "src": [
   1,
   578,
   418,
   576,
   384
  ]
 },
 "house4": {
  "tw": 15,
  "th": 13,
  "solid": [
   0,
   2,
   15,
   9
  ],
  "doors": [
   0.34
  ],
  "ground": "grass",
  "rot": true,
  "scene": true,
  "src": [
   1,
   482,
   0,
   480,
   416
  ]
 },
 "house5": {
  "tw": 14,
  "th": 10,
  "solid": [
   0,
   3,
   10,
   8
  ],
  "doors": [
   0.4
  ],
  "ground": "grass",
  "rot": true,
  "scene": true,
  "src": [
   1,
   804,
   1158,
   448,
   320
  ]
 },
 "house6": {
  "tw": 19,
  "th": 12,
  "solid": [
   2,
   2,
   17,
   8
  ],
  "doors": [
   0.5
  ],
  "ground": "grass",
  "rot": true,
  "scene": true,
  "src": [
   1,
   1156,
   418,
   608,
   384
  ]
 },
 "bank2": {
  "tw": 19,
  "th": 8,
  "solid": [
   0,
   0,
   19,
   6
  ],
  "doors": [
   0.45
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   2,
   610,
   902,
   608,
   256
  ]
 },
 "junkyard": {
  "tw": 19,
  "th": 10,
  "solid": [
   0,
   0,
   4,
   3
  ],
  "doors": [
   0.25
  ],
  "ground": "dirt",
  "rot": true,
  "scene": true,
  "src": [
   1,
   1254,
   1158,
   608,
   320
  ]
 },
 "tackle2": {
  "tw": 17,
  "th": 9,
  "solid": [
   1,
   0,
   13,
   5
  ],
  "doors": [
   0.45
  ],
  "ground": "dirt",
  "rot": false,
  "scene": true,
  "src": [
   2,
   1060,
   612,
   544,
   288
  ]
 },
 "shack": {
  "tw": 14,
  "th": 10,
  "solid": [
   0,
   0,
   14,
   7
  ],
  "doors": [
   0.5
  ],
  "ground": "dirt",
  "rot": true,
  "scene": true,
  "src": [
   1,
   0,
   1480,
   448,
   320
  ]
 },
 "farmstead": {
  "tw": 19,
  "th": 10,
  "solid": [
   11,
   1,
   17,
   5
  ],
  "doors": [
   0.2
  ],
  "ground": "dirt",
  "rot": true,
  "scene": true,
  "src": [
   1,
   450,
   1480,
   608,
   320
  ]
 },
 "site": {
  "tw": 18,
  "th": 13,
  "solid": [
   0,
   0,
   5,
   4
  ],
  "doors": [
   0.15
  ],
  "ground": "dirt",
  "rot": true,
  "scene": true,
  "src": [
   1,
   964,
   0,
   576,
   416
  ]
 },
 "beachbar": {
  "tw": 18,
  "th": 10,
  "solid": [
   4,
   1,
   12,
   5
  ],
  "doors": [
   0.45
  ],
  "ground": "sand",
  "rot": true,
  "scene": true,
  "src": [
   1,
   1060,
   1480,
   576,
   320
  ]
 },
 "pool": {
  "tw": 19,
  "th": 10,
  "solid": [
   0,
   0,
   5,
   5
  ],
  "doors": [
   0.12
  ],
  "ground": "grass",
  "rot": true,
  "scene": true,
  "src": [
   2,
   0,
   0,
   608,
   320
  ]
 },
 "liquor": {
  "tw": 14,
  "th": 10,
  "solid": [
   0,
   0,
   13,
   9
  ],
  "doors": [
   0.28
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   2,
   610,
   0,
   448,
   320
  ]
 },
 "shops1": {
  "tw": 24,
  "th": 7,
  "solid": [
   0,
   0,
   24,
   6
  ],
  "doors": [
   0.1,
   0.31,
   0.53,
   0.7,
   0.88
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   2,
   1220,
   902,
   768,
   224
  ]
 },
 "shops2": {
  "tw": 25,
  "th": 7,
  "solid": [
   0,
   0,
   25,
   6
  ],
  "doors": [
   0.1,
   0.31,
   0.57,
   0.74,
   0.91
  ],
  "ground": "plaza",
  "rot": false,
  "scene": true,
  "src": [
   2,
   0,
   1160,
   800,
   224
  ]
 }
};
export const GROUND_TEX = {"asphalt": [0, 0, 128, 128], "asphalt_worn": [128, 0, 128, 128], "concrete": [256, 0, 128, 128], "brick": [384, 0, 128, 128], "slate": [512, 0, 128, 128], "water": [640, 0, 128, 128], "deep": [768, 0, 128, 128], "grass": [896, 0, 128, 128], "sand": [1024, 0, 128, 128], "dirt": [1152, 0, 128, 128], "deck": [1280, 0, 128, 128]};
export const PROP_SIZES = {"tree_a": [63, 78], "tree_b": [63, 78], "palm_a": [59, 62], "palm_b": [55, 58], "palm_c": [55, 58], "palm_d": [50, 48], "shrub_a": [40, 39], "shrub_b": [32, 38], "palm_s": [38, 44], "flowerbed": [60, 44], "planter_sq": [31, 32], "planter_g": [33, 34], "bench_a": [40, 31], "bench_b": [40, 33], "bench_m": [40, 32], "trashcan": [10, 16], "dumpster_s": [42, 40], "mailbox": [14, 18], "dumpster_m": [50, 46], "planter_fl": [46, 40], "atm": [9, 20], "news_a": [9, 16], "news_b": [9, 16], "news_c": [10, 16], "hydrant": [10, 16], "hydrant_y": [9, 16], "cone": [10, 14], "bikerack": [30, 28], "bush_a": [24, 30], "bush_b": [23, 30], "bush_c": [34, 36], "umbrella_r": [36, 46], "umbrella_b": [29, 46], "umbrella_g": [30, 46], "umbrella_y": [31, 46], "foodcart": [33, 44], "foodcart_b": [31, 44], "stall": [66, 61], "vend_a": [10, 26], "vend_cola": [11, 26], "vend_c": [10, 26], "produce_a": [29, 30], "produce_b": [29, 30], "pbench": [42, 25], "flowers_a": [48, 33], "flowers_big": [43, 52], "fountain": [75, 84], "mosaic": [60, 49], "potted": [14, 24], "bags": [40, 21], "cart": [36, 28], "dump_g": [38, 46], "dump_b": [36, 46], "dump_o": [30, 46], "tires": [28, 40], "pallet_s": [28, 30], "pallet": [38, 36], "pipes": [46, 29], "rubble": [38, 31], "lumber": [60, 31], "barrier": [46, 29], "wheelbarrow": [36, 26], "gravel": [38, 31], "sandbags": [42, 39], "pallet_b": [44, 37], "drum": [13, 22], "spool": [23, 30], "planks": [36, 38], "roof_ac": [92, 79], "roof_heli": [150, 113], "roof_tanks": [96, 79], "roof_sky": [104, 79], "roof_access": [90, 68]};
export const VEHICLE_ART_SIZE = {"compact": [71, 52], "sedan": [81, 59], "taxi": [96, 50], "sports": [95, 48], "van": [102, 59], "pickup": [99, 56], "police": [96, 50], "swat": [114, 61], "ambulance": [102, 62], "bike": [49, 19], "speedboat": [103, 48], "dinghy": [83, 39], "flatbed": [140, 60], "boxtruck": [149, 58], "dumptruck": [139, 60], "mixer": [142, 62], "tanker": [147, 63], "garbage": [130, 64], "towtruck": [134, 58], "firetruck": [157, 72], "bus": [164, 70], "armored": [132, 50]};
