// GENERATED by tools/build_art.py - do not edit by hand.
// Building prefabs cut from the concept building sheet. Sizes/footprints are in tiles
// (32 world px); src is the rect inside assets/prefabs.png (drawn at 2 world px per source px).
export const PREFAB_SCALE = 2;
export const PREFABS = {
 "house1": {
  "tw": 7,
  "th": 14,
  "solid": [
   0,
   3,
   7,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   1715,
   0,
   115,
   227
  ]
 },
 "house2": {
  "tw": 7,
  "th": 14,
  "solid": [
   0,
   2,
   7,
   10
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   1832,
   0,
   107,
   227
  ]
 },
 "house3": {
  "tw": 6,
  "th": 14,
  "solid": [
   0,
   2,
   6,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   1941,
   0,
   99,
   227
  ]
 },
 "apt1": {
  "tw": 10,
  "th": 15,
  "solid": [
   1,
   1,
   9,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   1382,
   0,
   162,
   233
  ]
 },
 "apt2": {
  "tw": 10,
  "th": 15,
  "solid": [
   1,
   0,
   9,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   1546,
   0,
   167,
   233
  ]
 },
 "tower1": {
  "tw": 10,
  "th": 15,
  "solid": [
   1,
   0,
   10,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": true,
  "src": [
   929,
   0,
   157,
   237
  ]
 },
 "tower2": {
  "tw": 7,
  "th": 15,
  "solid": [
   0,
   0,
   7,
   13
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": true,
  "src": [
   1088,
   0,
   115,
   237
  ]
 },
 "hotel": {
  "tw": 11,
  "th": 15,
  "solid": [
   1,
   0,
   10,
   10
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   1205,
   0,
   175,
   237
  ]
 },
 "hospital": {
  "tw": 14,
  "th": 14,
  "solid": [
   0,
   0,
   14,
   11
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   207,
   243,
   227,
   219
  ]
 },
 "police": {
  "tw": 12,
  "th": 10,
  "solid": [
   1,
   0,
   11,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   1145,
   243,
   197,
   155
  ]
 },
 "fire": {
  "tw": 12,
  "th": 9,
  "solid": [
   1,
   0,
   12,
   9
  ],
  "doors": [
   0.4
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   1213,
   466,
   197,
   141
  ]
 },
 "gas": {
  "tw": 13,
  "th": 14,
  "solid": [
   8,
   0,
   13,
   3
  ],
  "doors": [
   0.8
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   0,
   243,
   205,
   221
  ]
 },
 "conv": {
  "tw": 13,
  "th": 9,
  "solid": [
   1,
   0,
   13,
   8
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   1561,
   243,
   210,
   151
  ]
 },
 "strip": {
  "tw": 17,
  "th": 9,
  "solid": [
   0,
   1,
   17,
   8
  ],
  "doors": [
   0.17,
   0.39,
   0.61,
   0.83
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   0,
   466,
   277,
   149
  ]
 },
 "market": {
  "tw": 17,
  "th": 9,
  "solid": [
   1,
   0,
   17,
   8
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   703,
   466,
   273,
   145
  ]
 },
 "rest1": {
  "tw": 10,
  "th": 13,
  "solid": [
   1,
   0,
   8,
   7
  ],
  "doors": [
   0.45
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   436,
   243,
   157,
   205
  ]
 },
 "rest2": {
  "tw": 9,
  "th": 13,
  "solid": [
   0,
   0,
   9,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   595,
   243,
   145,
   205
  ]
 },
 "club": {
  "tw": 11,
  "th": 13,
  "solid": [
   1,
   0,
   10,
   10
  ],
  "doors": [
   0.45
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   742,
   243,
   182,
   205
  ]
 },
 "bank": {
  "tw": 14,
  "th": 13,
  "solid": [
   1,
   0,
   13,
   12
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   926,
   243,
   217,
   205
  ]
 },
 "dealer": {
  "tw": 15,
  "th": 9,
  "solid": [
   3,
   0,
   14,
   9
  ],
  "doors": [
   0.57
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   978,
   466,
   233,
   145
  ]
 },
 "repair": {
  "tw": 13,
  "th": 10,
  "solid": [
   1,
   0,
   11,
   9
  ],
  "doors": [
   0.4
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   1344,
   243,
   215,
   155
  ]
 },
 "warehouse": {
  "tw": 12,
  "th": 9,
  "solid": [
   0,
   0,
   12,
   8
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   279,
   466,
   197,
   148
  ]
 },
 "industrial": {
  "tw": 19,
  "th": 15,
  "solid": [
   0,
   0,
   19,
   11
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": true,
  "src": [
   0,
   0,
   305,
   241
  ]
 },
 "construction": {
  "tw": 15,
  "th": 15,
  "solid": [
   4,
   1,
   15,
   11
  ],
  "doors": [
   0.15
  ],
  "ground": "dirt",
  "rot": true,
  "src": [
   307,
   0,
   235,
   241
  ]
 },
 "church": {
  "tw": 10,
  "th": 15,
  "solid": [
   1,
   0,
   9,
   11
  ],
  "doors": [
   0.5
  ],
  "ground": "plaza",
  "rot": false,
  "src": [
   544,
   0,
   164,
   241
  ]
 },
 "school": {
  "tw": 14,
  "th": 9,
  "solid": [
   0,
   0,
   14,
   9
  ],
  "doors": [
   0.5
  ],
  "ground": "lot",
  "rot": false,
  "src": [
   478,
   466,
   223,
   148
  ]
 },
 "park": {
  "tw": 14,
  "th": 15,
  "solid": [
   4,
   1,
   10,
   7
  ],
  "doors": [
   0.5
  ],
  "ground": "grass",
  "rot": true,
  "src": [
   710,
   0,
   217,
   241
  ]
 }
};
export const GROUND_TEX = {"asphalt": [0, 0, 128, 128], "asphalt_worn": [128, 0, 128, 128], "concrete": [256, 0, 128, 128], "brick": [384, 0, 128, 128], "slate": [512, 0, 128, 128], "water": [640, 0, 128, 128], "deep": [768, 0, 128, 128]};
export const PROP_SIZES = {"tree_a": [63, 78], "tree_b": [63, 78], "palm_a": [59, 62], "palm_b": [55, 58], "palm_c": [55, 58], "palm_d": [50, 48], "shrub_a": [40, 39], "shrub_b": [32, 38], "palm_s": [38, 44], "flowerbed": [60, 44], "planter_sq": [31, 32], "planter_g": [33, 34], "bench_a": [40, 31], "bench_b": [40, 33], "bench_m": [40, 32], "trashcan": [10, 16], "dumpster_s": [42, 40], "mailbox": [14, 18], "dumpster_m": [50, 46], "planter_fl": [46, 40], "atm": [9, 20], "news_a": [9, 16], "news_b": [9, 16], "news_c": [10, 16], "hydrant": [10, 16], "hydrant_y": [9, 16], "cone": [10, 14], "bikerack": [30, 28], "bush_a": [24, 30], "bush_b": [23, 30], "bush_c": [34, 36], "umbrella_r": [36, 46], "umbrella_b": [29, 46], "umbrella_g": [30, 46], "umbrella_y": [31, 46], "foodcart": [33, 44], "foodcart_b": [31, 44], "stall": [66, 61], "vend_a": [10, 26], "vend_cola": [11, 26], "vend_c": [10, 26], "produce_a": [29, 30], "produce_b": [29, 30], "pbench": [42, 25], "flowers_a": [48, 33], "flowers_big": [43, 52], "fountain": [75, 84], "mosaic": [60, 49], "potted": [14, 24], "bags": [40, 21], "cart": [36, 28], "dump_g": [38, 46], "dump_b": [36, 46], "dump_o": [30, 46], "tires": [28, 40], "pallet_s": [28, 30], "pallet": [38, 36], "pipes": [46, 29], "rubble": [38, 31], "lumber": [60, 31], "barrier": [46, 29], "wheelbarrow": [36, 26], "gravel": [38, 31], "sandbags": [42, 39], "pallet_b": [44, 37], "drum": [13, 22], "spool": [23, 30], "planks": [36, 38]};
export const VEHICLE_ART_SIZE = {"compact": [71, 52], "sedan": [81, 59], "taxi": [96, 50], "sports": [95, 48], "van": [102, 59], "pickup": [96, 57], "police": [97, 50], "swat": [114, 61], "ambulance": [102, 62], "bike": [49, 19], "speedboat": [103, 48], "dinghy": [83, 39], "bus": [164, 70], "armored": [132, 50]};
