"""Pets and strays cut from the character concept sheets (white background).

Usage: python3 tools/build_animals.py <concept_dir> [repo_root=.]

Outputs
  assets/animals.png       the sprites, transparent, packed in a row
  shared/animal-art.js     generated: rect [x, y, w, h] and view per animal
    view 'top'   - drawn from straight above, nose to the RIGHT (rotate it to face any way)
    view 'front' - a 3/4 view facing the camera (mirror it for left / right)
"""
import json
import os
import sys
import numpy as np
from PIL import Image
from scipy import ndimage

SRC = sys.argv[1] if len(sys.argv) > 1 else '.'
ROOT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), '..')

# (sheet, band y0..y1 in px, components in left-to-right order -> names (None = skip), view, rotate to face right)
BANDS = [
    ('ac05a82f-image.png', (880, 1020), ['dog_golden', 'dog_black', None, None, None, None], 'top', 90, 'from_right', 6),
    ('ac05a82f-image.png', (880, 1020), [None, None, 'dog_spaniel', 'dog_pup', None, None], 'front', 0, 'from_right', 6),
    ('52c77f7d-image.png', (885, 1015), ['dog_retriever', 'cat_black', 'cat_grey', None, None, 'cat_ginger'], 'front', 0, 'from_left', 6),
]
SCALE = 0.5   # sheet px -> art px (the game draws them at ~1 art px per world px)


def components(im, band, n, side):
    a = np.asarray(im.convert('RGB')).astype(int)[band[0]:band[1]]
    fg = (a.min(-1) < 235) | ((a.max(-1) - a.min(-1)) > 25)
    fg = ndimage.binary_closing(fg, np.ones((5, 5)))
    lab, k = ndimage.label(fg)
    boxes = []
    for i, sl in enumerate(ndimage.find_objects(lab)):
        h, w = sl[0].stop - sl[0].start, sl[1].stop - sl[1].start
        if h * w < 600:
            continue
        boxes.append((sl[1].start, sl[0].start + band[0], sl[1].stop, sl[0].stop + band[0], i + 1))
    boxes.sort(key=lambda b: b[0])
    if side == 'from_right':
        boxes = boxes[-n:]
    else:
        boxes = boxes[:n]
    return boxes, lab


def cut(im, box, band, lab):
    x0, y0, x1, y1, li = box
    rgb = im.convert('RGB').crop((x0, y0, x1, y1))
    mask = (lab[y0 - band[0]:y1 - band[0], x0:x1] == li)
    mask = ndimage.binary_dilation(mask, iterations=1)
    out = rgb.convert('RGBA')
    out.putalpha(Image.fromarray((mask * 255).astype(np.uint8)))
    return out


def main():
    sprites = {}
    for sheet, band, names, view, rot, side, n in BANDS:
        im = Image.open(os.path.join(SRC, sheet))
        boxes, lab = components(im, band, n, side)
        if side == 'from_right':
            names = names[-len(boxes):] if len(boxes) < len(names) else names
            boxes = boxes[-len(names):]
        for name, box in zip(names, boxes):
            if not name:
                continue
            sp = cut(im, box, band, lab)
            if rot:
                sp = sp.rotate(-rot, expand=True)  # nose up -> nose right
            sp = sp.resize((max(1, round(sp.width * SCALE)), max(1, round(sp.height * SCALE))), Image.LANCZOS)
            sprites[name] = (sp, view)
    W = sum(s.width + 2 for s, _ in sprites.values())
    H = max(s.height for s, _ in sprites.values())
    sheet = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    rects, x = {}, 0
    for name, (sp, view) in sprites.items():
        sheet.paste(sp, (x, 0), sp)
        rects[name] = {'r': [x, 0, sp.width, sp.height], 'view': view}
        x += sp.width + 2
    sheet.save(os.path.join(ROOT, 'assets', 'animals.png'), optimize=True)
    js = ('// Generated by tools/build_animals.py - do not edit.\n'
          '// Pet / stray sprites in assets/animals.png: r = [x, y, w, h]; view top = from above, nose right; front = 3/4, facing the camera.\n'
          f'export const ANIMAL_ART = {json.dumps(rects)};\n')
    with open(os.path.join(ROOT, 'shared', 'animal-art.js'), 'w') as f:
        f.write(js)
    print('animals', list(rects))


if __name__ == '__main__':
    main()
