"""Turn the world map concept (tools/data/worldmap-concept.webp) into the game's land and terrain
data (shared/worldmask.js). One concept pixel = one 32 px tile; the world is 1312 x 1200 tiles.

    python3 tools/build-worldmask.py            (needs numpy, scipy, Pillow)

Output, both run-length encoded so the file stays small and the browser decodes it instantly:
  LAND     1 = land, 0 = sea. Bridges and piers in the painting are removed (the generator lays
           its own), the scalloped painted coast is rounded off, specks smaller than a cove are dropped.
  TERRAIN  one class per 4x4-tile cell, read from the painting's colours, for the wild parts of the
           world that aren't built up yet: g grass, f forest, d desert, r rock / mountain, s sand.
Run-length format: rows separated by '|', each row alternating run lengths in base 36, starting
with a run of 0 (sea) - LAND; TERRAIN rows are '<class><len36>' pairs.
"""
import os
import numpy as np
from PIL import Image
from scipy import ndimage as nd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W, H = 1312, 1200
CELL = 4


def b36(n):
    s = ''
    digits = '0123456789abcdefghijklmnopqrstuvwxyz'
    if n == 0:
        return '0'
    while n:
        s = digits[n % 36] + s
        n //= 36
    return s


def main():
    im = Image.open(os.path.join(ROOT, 'tools', 'data', 'worldmap-concept.webp')).convert('RGB')
    a = np.zeros((H, W, 3), dtype=np.int32)
    src = np.asarray(im).astype(np.int32)
    a[:src.shape[0], :src.shape[1]] = src[:H, :W]
    a[src.shape[0]:, :] = (10, 70, 140)  # pad the last row(s) with sea
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    wet = (b > r + 25) & (b > g - 5)
    # the sea: wet pixels connected to the edge of the map (blue glass towers inland stay land).
    # Bridges cut the channels into basins, so close them over first.
    disk = lambda rad: (lambda y, x: x * x + y * y <= rad * rad)(*np.ogrid[-rad:rad + 1, -rad:rad + 1])
    wet = nd.binary_closing(wet, structure=disk(4)) | wet
    lab, _ = nd.label(wet)
    edge = set(np.unique(np.concatenate([lab[0], lab[-1], lab[:, 0], lab[:, -1]]))) - {0}
    sea = np.isin(lab, list(edge))
    land = ~sea
    # drop bridges, piers and thin spits (opening), then round the painted scallops off
    land = nd.binary_opening(land, structure=disk(6))
    land = nd.gaussian_filter(land.astype(np.float32), 2.2) > 0.5
    land = nd.binary_fill_holes(land)
    lab, n = nd.label(land)
    sizes = nd.sum(land, lab, range(1, n + 1))
    keep = np.zeros(n + 1, bool)
    keep[1:] = sizes >= 220
    land = keep[lab]
    land[:6, :] = False; land[-6:, :] = False; land[:, :6] = False; land[:, -6:] = False

    rows = []
    for y in range(H):
        row = land[y]
        runs, cur, k = [], False, 0
        for v in row:
            if v == cur:
                k += 1
            else:
                runs.append(k); cur = v; k = 1
        runs.append(k)
        rows.append(','.join(b36(x) for x in runs))

    # terrain classes from the painting, per 4x4 cell (mean colour of the cell's land pixels)
    cw, ch = W // CELL, H // CELL
    cls = []
    af = a.astype(np.float32)
    for cy in range(ch):
        line = []
        for cx in range(cw):
            blk = af[cy * CELL:(cy + 1) * CELL, cx * CELL:(cx + 1) * CELL].reshape(-1, 3)
            lm = land[cy * CELL:(cy + 1) * CELL, cx * CELL:(cx + 1) * CELL].reshape(-1)
            if lm.sum() == 0:
                line.append('w'); continue
            R, G, B = blk[lm].mean(axis=0)
            mx, mn = max(R, G, B), min(R, G, B)
            sat = (mx - mn) / (mx + 1)
            if R > 150 and G > 110 and R > G + 12 and B < G - 10:
                c = 'd'  # desert / dry sand
            elif sat < 0.22 and 60 < mx < 175 and R >= G - 8:
                c = 'r'  # rock, mountains (also grey city blocks: built over anyway)
            elif G > R + 4 and G < 105:
                c = 'f'  # dark green: forest
            elif G >= R:
                c = 'g'
            elif R > 160 and G > 140:
                c = 's'
            else:
                c = 'r'
            line.append(c)
        out, prev, k = [], line[0], 0
        for c in line:
            if c == prev:
                k += 1
            else:
                out.append(prev + b36(k)); prev = c; k = 1
        out.append(prev + b36(k))
        cls.append(''.join(out))

    js = ('// Generated by tools/build-worldmask.py from the world map concept - do not edit by hand.\n'
          '// Land / sea and wild terrain for the whole world (see the tool for the format).\n'
          f'export const MASK_W = {W}, MASK_H = {H}, TERRAIN_CELL = {CELL};\n'
          f"export const LAND = '{'|'.join(rows)}';\n"
          f"export const TERRAIN = '{'|'.join(cls)}';\n")
    with open(os.path.join(ROOT, 'shared', 'worldmask.js'), 'w') as f:
        f.write(js)
    print('shared/worldmask.js', len(js) // 1024, 'KB, land', round(land.mean() * 100, 1), '%')
    prev = np.zeros((H, W, 3), np.uint8)
    prev[land] = (90, 160, 80)
    prev[~land] = (20, 60, 130)
    Image.fromarray(prev).save(os.environ.get('PREVIEW', '/tmp/worldmask.png'))


main()
