"""The instruments' loudness by category (tools/sound/bench.py --levels).

Every instrument is measured alone (unplaced, vol 1, dry): its loudest 200 ms, A-weighted, in dB below full scale.
Each category has a target and a range (the targets keep the categories in their order - explosions loudest, then
guns, the usual effects, the menus, footsteps, the world around - near where most of each already sat, so the trims
even out the stragglers rather than turn everything up); an instrument's trim (dB, applied by client/sound/engine.js
play) brings it to its category's target, within the trim's limits, and never lifts its peak past PEAK_MAX. The table goes to client/sound/levels.js (what the engine uses) and
test/fixtures/sound-levels.json (what test/sound.test.js checks: the measurement, the trim, and the result in range).
"""
import json
import os

# the categories: (target, low, high) for the loudest 200 ms, dBA below full scale, at vol 1 before the buses
CATS = {
    'boom': (-20, -25, -17),     # explosions, thunder, rock falls, a tree crashing down: the loudest (the thumpiest held back by their peaks)
    'gun': (-25, -28, -22),      # guns: loud but short
    'fx': (-32, -36, -28),       # the usual: hits, doors, crashes, voices, tools
    'ui': (-35, -39, -31),       # the menus, the phone, money, the stars: quiet, clear
    'step': (-38, -42, -34),     # footsteps, strokes, leaves: quiet
    'amb': (-40, -45, -35),      # critters and the town far off, drops, crackle: under the effects
}
TARGET = {k: v[0] for k, v in CATS.items()}
RANGE = {k: (v[1], v[2]) for k, v in CATS.items()}
TRIM_MIN, TRIM_MAX = -20.0, 20.0
PEAK_MAX = 3.0   # (dBFS at vol 1, before the buses - about -7 dBFS at the master with the default levels: a trim never lifts a peak past it)

UI = {'click', 'notify', 'good', 'bad', 'alert', 'phoneopen', 'phoneclose', 'coin', 'cashin', 'cashout', 'starup', 'stardown',
      'death', 'goal', 'racego', 'checkpoint', 'ridebell', 'bite', 'reloadout', 'reloadin'}
STEP = {'step', 'stroke', 'leaves', 'twig'}
AMB = {'cricket', 'owl', 'bird', 'gull', 'dog', 'farsiren', 'farhorn', 'drop', 'crackle', 'cavedrip', 'squeak', 'drip', 'slidingdoor',
       'clack', 'trickle', 'flutter'}
GUN = {'gun_pistol', 'gun_revolver', 'gun_smg', 'gun_rifle', 'gun_shotgun', 'gun_sniper', 'gun_rocket'}
BOOM = {'explosion', 'thunder', 'rockfall', 'treefall'}


def category(name):
    if name in UI:
        return 'ui'
    if name in STEP:
        return 'step'
    if name in AMB:
        return 'amb'
    if name in GUN:
        return 'gun'
    if name in BOOM:
        return 'boom'
    return 'fx'


def trim_for(name, loud, peak):
    t = min(TARGET[category(name)] - loud, PEAK_MAX - peak)
    return round(max(TRIM_MIN, min(TRIM_MAX, t)), 1)


def write(raw, root):
    """raw: bench.js runInstruments({ raw: true }) - each recipe measured before its trim."""
    table = {}
    for name in sorted(raw):
        v = raw[name]
        c = category(name)
        tr = trim_for(name, v['max200'], v['peak'])
        table[name] = {'cat': c, 'loud': v['max200'], 'peak': v['peak'], 'trim': tr, 'after': round(v['max200'] + tr, 1)}
    fx = {'categories': {k: {'target': t, 'low': lo, 'high': hi} for k, (t, lo, hi) in CATS.items()}, 'trimLimits': [TRIM_MIN, TRIM_MAX], 'peakMax': PEAK_MAX,
          'measure': 'loudest 200 ms, A-weighted RMS, dB below full scale; unplaced, vol 1, dry, 48 kHz (tools/sound/bench.js)', 'instruments': table}
    os.makedirs(os.path.join(root, 'test', 'fixtures'), exist_ok=True)
    with open(os.path.join(root, 'test', 'fixtures', 'sound-levels.json'), 'w') as f:
        json.dump(fx, f, indent=1)
        f.write('\n')
    lines = ['// Each instrument\'s level trim in dB (generated by tools/sound/bench.py --levels from a render of every recipe alone:',
             '// its loudest 200 ms, A-weighted, brought to its category\'s target - test/fixtures/sound-levels.json has the',
             '// measurements; test/sound.test.js checks them). engine.js play multiplies a sound\'s volume by its trim.',
             'export const TRIM_DB = Object.freeze({']
    row = []
    for name in sorted(table):
        row.append(f"{name}: {table[name]['trim']}")
        if len(row) == 8:
            lines.append('  ' + ', '.join(row) + ',')
            row = []
    if row:
        lines.append('  ' + ', '.join(row) + ',')
    lines.append('});')
    with open(os.path.join(root, 'client', 'sound', 'levels.js'), 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote client/sound/levels.js and test/fixtures/sound-levels.json')
